name: Deploy nginx via Jenkins

on:
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger Jenkins
      run: |
        curl -X POST \
          "https://cg-stg-jenkins-su.glb.samsung-gamelauncher.com/job/deploy-nginx-to-gke-cluster/buildWithParameters" \
          --user "ducgiang-ng:1195aa226849b0bee760aeb4bf4a80d2b3" \
          --data IMAGE_TAG=5f6893e8a4aa0ceb8a094a0d8675e681fe8cad1
